(() => {
  'use strict';
  const $=id=>document.getElementById(id),root=$('rpgQuest');
  const encounters=[
    {name:'空等史萊姆',area:'翠葉草原',x:4,y:7,color:'#83d5ba',skill:'分割與刪除',steps:['把播放頭移到 3 秒，分割空等片段。','點選兩段空等，分別刪除。保留目的、動作與結果。','完整播放你的影片，再發動剪輯反擊。']},
    {name:'迷霧石狼',area:'月影森林',x:9,y:3,color:'#aab5e9',skill:'鏡頭順序與景別',steps:['先選「發現怪物」，用往前把它放在「勇者反應」之前。','選中景，同時看見勇者和怪物所在的位置。','結尾至少留 2 秒，讓人看到拿回星石的結果。']},
    {name:'墨影巨鴞',area:'古老書塔',x:12,y:6,color:'#c295d7',skill:'字幕與聲音',steps:['為閃躲鏡頭寫一句不超過 16 字的字幕。','把字幕移到下方，避開勇者與怪物。','背景音樂降到 25% 以下，重要提示音保持 70% 以上。']},
    {name:'回聲巨龍',area:'回聲城堡',x:14,y:2,color:'#eda38a',skill:'綜合剪輯實戰',steps:['刪掉空等片段，但保留線索、關鍵動作與結果。','先點趕路調成 2 倍速；閃躲保持 1 倍，別把重要動作也加快。','從頭完整播放冒險。讓影片交代目的、危機、解決與結果，再出招。']}
  ];
  root.innerHTML='<div class="rpg-shell"><div class="rpg-heading"><div><span class="eyebrow">STORY QUEST / 20 MIN</span><h2>回聲王國：剪輯勇者的遠征</h2><p>探索地圖、收集星石、回合戰鬥。你的剪輯，是勇者真正的招式。</p></div><span id="rpgProgress" class="arcade-score">星石 0 / 4</span></div><div class="rpg-grid"><div><div class="rpg-hud"><span id="rpgHealth">勇者 ♥ ♥ ♥ ♥</span><b id="rpgLocation">星光營地</b></div><div class="rpg-stage"><canvas id="rpgCanvas" width="800" height="500" tabindex="0" aria-label="勇者冒險地圖。方向鍵移動，Enter 與附近角色對話或開始戰鬥。也可點怪物旗子或下方地區卡。"></canvas></div><div class="rpg-pad"><button data-rpg-move="up" aria-label="勇者往上">↑</button><button data-rpg-move="left" aria-label="勇者往左">←</button><button data-rpg-move="down" aria-label="勇者往下">↓</button><button data-rpg-move="right" aria-label="勇者往右">→</button><button id="rpgInteract">對話／遭遇</button><button id="rpgMap" class="quiet">回地圖</button><button id="rpgRetry" class="quiet">重玩此遭遇</button><button id="rpgRest" class="quiet">回營地補血</button><label class="note" style="margin:0"><input id="rpgSound" type="checkbox"> 試聽勇者音軌</label></div><div id="rpgLog" class="rpg-log" role="status"></div></div><aside class="rpg-mission"><span id="rpgTurn" class="eyebrow">ADVENTURE LOG</span><h3 id="rpgTitle">王國的影片，失去了故事</h3><p id="rpgInstruction">四隻怪物把影片變得拖延、混亂或看不清楚。走到旗子附近，帶回星石。營地的旅人也有線索。</p><div id="rpgSettings"></div><button id="rpgAttack">發動剪輯反擊 ✦</button><p id="rpgConnection" class="rpg-tooltip">同樣的操作，也會用在剪映的時間軸裡。</p></aside></div><div id="rpgMonsters" class="rpg-monsters"></div><section class="rpg-cutboard" aria-label="勇者戰鬥剪輯時間軸"><div class="rpg-tools"><span>戰鬥剪輯台 · 影片軌</span><button id="rpgSplit">✂ 分割</button><button id="rpgDelete">刪除選取</button><button id="rpgLeft">← 往前</button><button id="rpgRight">往後 →</button><button id="rpgPlay">▶ 播放冒險</button><button id="rpgRewind" class="quiet">回到開頭</button></div><label class="note">播放頭 <span id="rpgTime">0.0s</span><input id="rpgScrub" type="range" aria-label="勇者剪輯播放頭" min="0" max="1" step=".1" value="0"></label><div id="rpgTrack" class="rpg-track"></div><div id="rpgCaptionTrack" class="rpg-caption-track">字幕軌 · 還沒加入字幕</div><div class="rpg-tooltip">先看怪物造成什麼問題 → 動手修改影片 → 預覽 → 反擊。答錯不會消失，可以修好再試。</div></section></div>';
  root.querySelector('.rpg-mission').appendChild(root.querySelector('.rpg-cutboard'));root.querySelector('.rpg-grid>div').classList.add('rpg-player');
  const canvas=$('rpgCanvas'),ctx=canvas.getContext('2d');
  let player={x:2,y:8},active=-1,turn=0,hp=4,enemyHP=100,clips=[],selected=null,uid=0,head=0,split=false,caption='',position='center',framing='wide',music=60,cue=90;
  let playing=false,fullWatch=false,watchStart=false,anim=0,last=0,time=0,visible=false,flash=0,particles=[],walking=0,preview=false;
  const won=new Set(),rewards=[];
  function node(tag,text,parent,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;parent.appendChild(n);return n;}
  function log(text){$('rpgLog').textContent=text;}
  function clip(id,name,sec){return {id,name,key:++uid,in:0,out:sec,speed:1};}
  function duration(s){return(s.out-s.in)/s.speed;}
  function total(){return clips.reduce((a,s)=>a+duration(s),0);}
  function pause(){playing=false;if(gain)gain.gain.value=0;if(bellGain)bellGain.gain.value=0;$('rpgPlay').textContent='▶ 播放冒險';}
  function stopEdit(){pause();preview=false;fullWatch=false;watchStart=false;}
  function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);}
  function hero(x,y,scale=1,pose='idle'){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const stride=pose==='run'?Math.sin(time*11)*7:0;rect(-10,0,8,13+stride,'#324965');rect(3,0,8,13-stride,'#324965');rect(-16,-29,32,30,'#588bc0');rect(-11,-23,22,17,'#36659b');rect(-3,-20,7,11,'#ffd576');rect(-22,-27,7,22+stride,'#eebc9b');rect(16,-27,7,22-stride,'#f5c6a0');rect(-13,-53,26,24,'#f2c9a3');rect(-15,-57,30,9,'#614c64');rect(-15,-53,6,15,'#614c64');rect(-7,-46,3,4,'#273750');rect(5,-46,3,4,'#273750');rect(-3,-35,9,2,'#a65b60');rect(19,-14,4,30,'#f5da8c');ctx.restore();}
  function monster(x,y,index,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const color=encounters[index].color;ctx.fillStyle='#05172555';ctx.beginPath();ctx.ellipse(0,12,43,12,0,0,7);ctx.fill();ctx.fillStyle=color;
    if(index===0){ctx.beginPath();ctx.moveTo(-40,4);ctx.quadraticCurveTo(-46,-29,-16,-44);ctx.lineTo(0,-65);ctx.lineTo(15,-44);ctx.quadraticCurveTo(49,-25,40,4);ctx.closePath();ctx.fill();}
    if(index===1){rect(-35,-43,70,48,color);ctx.beginPath();ctx.moveTo(-33,-43);ctx.lineTo(-26,-77);ctx.lineTo(-6,-43);ctx.lineTo(10,-43);ctx.lineTo(29,-77);ctx.lineTo(36,-43);ctx.fill();rect(-31,3,19,17,'#727fa8');rect(15,3,19,17,'#727fa8');}
    if(index===2){ctx.beginPath();ctx.ellipse(0,-30,39,51,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-26,-60);ctx.lineTo(-40,-91);ctx.lineTo(-7,-72);ctx.moveTo(26,-60);ctx.lineTo(40,-91);ctx.lineTo(7,-72);ctx.fill();rect(-52,-37,18,39,'#8970ad');rect(35,-37,18,39,'#8970ad');}
    if(index===3){rect(-32,-56,64,69,color);rect(-20,-83,40,38,color);ctx.beginPath();ctx.moveTo(-27,-35);ctx.lineTo(-85,-89);ctx.lineTo(-71,9);ctx.lineTo(-24,5);ctx.moveTo(27,-35);ctx.lineTo(85,-89);ctx.lineTo(71,9);ctx.lineTo(24,5);ctx.fill();rect(-20,-97,7,20,'#ffd78a');rect(14,-97,7,20,'#ffd78a');}
    ctx.fillStyle='#fff4d2';ctx.beginPath();ctx.ellipse(-15,-29,9,12,0,0,7);ctx.ellipse(15,-29,9,12,0,0,7);ctx.fill();rect(-15,-31,4,7,'#293651');rect(12,-31,4,7,'#293651');rect(-5,-10,12,3,'#584569');ctx.restore();}
  function tree(x,y){rect(x+16,y+24,8,21,'#715d45');ctx.fillStyle='#28594b';ctx.beginPath();ctx.moveTo(x+2,y+30);ctx.lineTo(x+20,y-5);ctx.lineTo(x+39,y+30);ctx.fill();ctx.fillStyle='#3c7755';ctx.beginPath();ctx.moveTo(x+6,y+19);ctx.lineTo(x+20,y-13);ctx.lineTo(x+34,y+19);ctx.fill();}
  function map(){rect(0,0,800,500,'#3e6b55');for(let y=0;y<10;y++)for(let x=0;x<16;x++){rect(x*50+12,y*50+31,3,6,'#5b8661');if(y===0||y===9||x===0||x===15)tree(x*50,y*50);}rect(40,390,190,28,'#b5a171');rect(205,160,30,246,'#b5a171');rect(215,160,500,28,'#b5a171');rect(455,160,25,165,'#b5a171');rect(460,310,265,26,'#b5a171');rect(655,90,27,230,'#b5a171');rect(275,45,45,405,'#3f8094');rect(265,157,65,37,'#9e7951');for(let i=0;i<4;i++)rect(267,160+i*8,61,3,'#dec393');
    for(const [x,y]of[[7,2],[8,2],[10,2],[9,4],[10,4],[11,5]])tree(x*50,y*50);rect(610,270,82,51,'#b6a7c6');rect(610,255,20,65,'#8b7d9b');rect(673,255,20,65,'#8b7d9b');rect(645,290,17,31,'#3c3b59');rect(675,80,64,62,'#a6a9bc');rect(662,65,20,88,'#737e99');rect(730,65,20,88,'#737e99');rect(698,110,22,43,'#394b67');
    const campX=125,campY=425;hero(campX,campY,.7);rect(90,418,15,10,'#e5a976');rect(92,402,10,19,'#ffe6a6');ctx.font='13px sans-serif';ctx.fillStyle='#fff1c2';ctx.fillText('營地／旅人',70,456);
    encounters.forEach((e,i)=>{const x=e.x*50+25,y=e.y*50+25;monster(x,y,i,.55);rect(x+22,y-48,3,44,'#efdaa8');rect(x+25,y-48,24,17,won.has(i)?'#a4ebca':'#f4ce83');ctx.fillStyle='#283a4b';ctx.font='bold 13px sans-serif';ctx.fillText(won.has(i)?'✓':String(i+1),x+31,y-35);ctx.fillStyle='#f6edcd';ctx.textAlign='center';ctx.font='12px sans-serif';ctx.fillText(e.name,x,y+28);});ctx.textAlign='left';hero(player.x*50+25,player.y*50+30,1,walking>time?'run':'idle');}
  function battle(){const e=encounters[active];const sky=ctx.createLinearGradient(0,0,0,500);sky.addColorStop(0,active===3?'#352941':'#20384d');sky.addColorStop(1,'#576c65');ctx.fillStyle=sky;ctx.fillRect(0,0,800,500);for(let i=0;i<6;i++)tree(i*140,160);rect(0,315,800,185,'#304d46');ctx.strokeStyle='#91a79133';for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(0,335+i*24);ctx.lineTo(800,335+i*24);ctx.stroke();}
    let acc=0,s=null,idx=-1;for(let i=0;i<clips.length;i++){if(head<acc+duration(clips[i])||i===clips.length-1){s=clips[i];idx=i;break;}acc+=duration(clips[i]);}const t=s?Math.min(1,Math.max(0,((head-acc)*s.speed+s.in)/s.out)):0;
    ctx.save();if(framing==='medium'&&preview){ctx.translate(-70,-65);ctx.scale(1.15,1.15);}const mx=550,my=313+(preview&&s?.id==='act'?Math.sin(t*12)*5:0);monster(mx,my,active,active===3?1.55:1.4);const hx=preview&&s?.id==='move'?180+t*120:preview&&s?.id==='act'?260+Math.sin(t*Math.PI)*100:210;const hy=preview&&s?.id==='act'?320-Math.sin(t*Math.PI)*75:320;hero(hx,hy,1.6,preview&&['move','act'].includes(s?.id)?'run':'idle');ctx.restore();
    ctx.fillStyle='#fff0ce';ctx.font='bold 18px sans-serif';ctx.fillText(e.area+' / '+e.name,24,36);rect(440,67,300,13,'#0b1727');rect(440,67,enemyHP*3,13,e.color);ctx.font='13px sans-serif';ctx.fillText('怪物生命 '+enemyHP+' / 100',442,60);
    if(preview&&s){rect(18,390,764,83,'#0a1e2cd9');ctx.fillStyle='#ccdfec';ctx.font='17px sans-serif';ctx.fillText('正在播放：'+s.name+'　'+head.toFixed(1)+' / '+total().toFixed(1)+' 秒',32,418);if(s.id==='clue'){ctx.strokeStyle='#ffe19b';ctx.lineWidth=3;ctx.strokeRect(470,185,165,140);}if(s.id==='act'&&caption){const yy=position==='bottom'?452:273;const width=Math.min(720,caption.length*19+30);rect((800-width)/2,yy-22,width,33,'#061423dd');ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='18px sans-serif';ctx.fillText(caption,400,yy+2);ctx.textAlign='left';}}
    [...$('rpgTrack').children].forEach((n,i)=>n.classList.toggle('playing',preview&&i===idx));}
  function draw(dt=0){ctx.clearRect(0,0,800,500);if(active<0)map();else battle();if(flash>0){ctx.fillStyle='#fff1b5';ctx.globalAlpha=flash*.35;ctx.fillRect(0,0,800,500);ctx.globalAlpha=1;flash=Math.max(0,flash-dt*2);}particles=particles.filter(p=>p.life>0);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;p.life-=dt;ctx.globalAlpha=Math.max(0,p.life);rect(p.x,p.y,5,5,p.color);}ctx.globalAlpha=1;}
  function fx(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;flash=.8;for(let i=0;i<35;i++)particles.push({x:550,y:230,vx:(Math.random()-.5)*350,vy:(Math.random()-.5)*300,life:.5+Math.random()*.5,color:'#fce2a1'});}
  function health(){$('rpgHealth').textContent='勇者 '+('♥ '.repeat(hp))+('♡ '.repeat(4-hp));$('rpgProgress').textContent='星石 '+won.size+' / 4';}
  function cards(){$('rpgMonsters').replaceChildren();encounters.forEach((e,i)=>{const b=node('button',(won.has(i)?'✓ ':'0'+(i+1)+' ')+e.area,$('rpgMonsters'),won.has(i)?'passed':'');node('small',e.name+' · '+e.skill,b);b.onclick=()=>{player={x:e.x-1,y:e.y};encounter(i);};});}
  function encounter(i){$('moreWorlds').open=false;$('editStop').click();pause();active=i;turn=0;enemyHP=100;head=0;split=false;fullWatch=false;watchStart=false;preview=false;caption='';position='center';framing='wide';music=60;cue=90;uid=0;
    clips=i===0?[clip('goal','取回星石的目的',2),clip('wait','空等',4),clip('act','閃躲怪物',3),clip('win','星石與歡呼',2)]:i===1?[clip('goal','取回星石的目的',2),clip('act','勇者反應',3),clip('clue','發現怪物',2),clip('win','星石與歡呼',1)]:[clip('goal','取回星石的目的',2),...(i===3?[clip('move','趕路',3),clip('wait','空等',4)]:[]),clip('clue','發現怪物',2),clip('act','閃躲怪物',3),clip('win','星石與歡呼',2)];selected=clips[0].key;$('rpgLocation').textContent=encounters[i].area;render();log('遭遇 '+encounters[i].name+'！它有三層防護。修好影片，每回合都能反擊。');ensure();}
  function tracks(){$('rpgTrack').replaceChildren();let acc=0;clips.forEach((s,i)=>{const start=acc;acc+=duration(s);const b=node('button',s.name,$('rpgTrack'),' '+(s.id==='wait'?'wait ':'')+(s.key===selected?'selected':''));b.setAttribute('aria-label','勇者選取 '+s.name+' 片段 '+(i+1));node('small',duration(s).toFixed(1)+'s · '+s.speed+'×',b);b.onclick=()=>{pause();preview=true;selected=s.key;head=start;watchStart=false;tracks();settings();draw();};});$('rpgScrub').max=total()||1;$('rpgScrub').value=head;$('rpgTime').textContent=head.toFixed(1)+'s / '+total().toFixed(1)+'s';$('rpgCaptionTrack').textContent='字幕軌 · '+(caption||'還沒加入字幕');for(const id of ['rpgSplit','rpgDelete','rpgLeft','rpgRight'])$(id).disabled=active<0||turn>=3;$('rpgPlay').disabled=active<0||!clips.length;}
  function settingSelect(label,options,value,onchange){const wrap=node('label',label,$('rpgSettings')),s=node('select',null,wrap);s.setAttribute('aria-label',label);for(const [v,text]of options){const n=node('option',text,s);n.value=v;}s.value=value;s.onchange=()=>{stopEdit();onchange(s.value);preview=true;tracks();draw();};}
  function slider(label,min,max,value,onchange){const wrap=node('label',label,$('rpgSettings')),s=node('input',null,wrap);s.type='range';s.min=min;s.max=max;s.step=1;s.value=value;s.setAttribute('aria-label',label.split('：')[0]);s.oninput=()=>{stopEdit();onchange(Number(s.value));wrap.firstChild.textContent=label.split('：')[0]+'：'+s.value;tracks();draw();};}
  function settings(){const r=$('rpgSettings');r.replaceChildren();if(active<0||turn>=3)return;const s=clips.find(n=>n.key===selected);node('p','選取：'+(s?.name||'無'),r,'note');
    if(active===1&&turn===1)settingSelect('勇者鏡頭景別',[['wide','全景'],['close','特寫'],['medium','中景：角色與怪物']],framing,v=>framing=v);
    if(active===1&&turn===2){const win=clips.find(n=>n.id==='win');if(win)slider('結尾停留秒數：'+win.out,1,4,win.out,v=>win.out=v);}
    if(active===2&&turn===0){const label=node('label','勇者字幕',r),input=node('input',null,label);input.type='text';input.maxLength=16;input.setAttribute('aria-label','勇者字幕');input.value=caption;input.oninput=()=>{stopEdit();caption=input.value;tracks();preview=true;head=clips.slice(0,clips.findIndex(n=>n.id==='act')).reduce((a,n)=>a+duration(n),0)+.8;draw();};}
    if(active===2&&turn===1)settingSelect('勇者字幕位置',[['center','中央：容易遮住動作'],['bottom','下方：避開主角']],position,v=>{position=v;preview=true;});
    if(active===2&&turn===2){slider('勇者背景音樂：'+music,0,100,music,v=>music=v);slider('勇者提示音：'+cue,0,100,cue,v=>cue=v);}
    if(active===3&&turn===1&&s)settingSelect('勇者片段速度',[['1','1 倍速'],['2','2 倍速']],String(s.speed),v=>s.speed=Number(v));
  }
  function render(){health();cards();tracks();settings();$('rpgAttack').disabled=active<0||turn>=3;if(active<0)return;const e=encounters[active];$('rpgTurn').textContent='ROUND '+Math.min(3,turn+1)+' / 3';$('rpgTitle').textContent=e.name; $('rpgInstruction').textContent=turn>=3?'星石收好了！回地圖前往其他地區。四顆集齊後，下載你的冒險素材筆記。':e.steps[turn];$('rpgConnection').textContent='剪映裡的同一招：'+e.skill+'。你的時間軸修改會真的改變播放的畫面與長度。';draw();}
  function mistake(text){hp=Math.max(0,hp-1);health();fx();log('怪物反擊，勇者 -1 ♥。'+text);if(hp===0){hp=4;health();log('旅人把你救回來，生命補滿。保留這次剪輯，修好再試：'+text);}}
  $('rpgAttack').onclick=()=>{if(active<0||turn>=3)return;let bad='';const ids=clips.map(n=>n.id);
    if(active===0&&turn===0&&!split)bad='在空等中間分割，不能只切到別的鏡頭。';if(active===0&&turn===1&&(ids.includes('wait')||!['goal','act','win'].every(id=>ids.includes(id))))bad='把空等拿掉，目的、動作與結果要留下。';
    if(active===1&&turn===0&&(!ids.includes('clue')||!ids.includes('act')||ids.indexOf('clue')>ids.indexOf('act')))bad='先讓人看到怪物，再看勇者的反應。';if(active===1&&turn===1&&framing!=='medium')bad='用中景，角色和怪物的位置都要看得到。';if(active===1&&turn===2&&(!ids.includes('win')||duration(clips.find(n=>n.id==='win'))<2))bad='留至少 2 秒，讓觀眾看見結果。';
    if(active===2&&turn===0&&!caption.trim())bad='先加一句幫忙看懂閃躲的短字幕。';if(active===2&&turn===1&&position!=='bottom')bad='字幕移到下方，別蓋住主角。';if(active===2&&turn===2&&(music>25||cue<70))bad='音樂退到 25% 以下，提示音保留 70% 以上。';
    if(active===3&&turn===0&&(ids.includes('wait')||!['goal','move','clue','act','win'].every(id=>ids.includes(id))))bad='只刪多餘的等待，別連事情的原因與結果一起拿掉。';if(active===3&&turn===1&&(clips.find(n=>n.id==='move')?.speed!==2||clips.find(n=>n.id==='act')?.speed!==1))bad='趕路可加速，閃躲動作維持 1 倍。';if((active===0||active===3)&&turn===2&&!fullWatch)bad='從頭完整播放修改後的冒險，確認故事沒有斷掉。';
    const essential=active===0?['goal','act','win']:active===3?['goal','move','clue','act','win']:['goal','clue','act','win'];if(!essential.every(id=>ids.includes(id)))bad='故事的目的、線索、動作或結果不見了。按重玩此遭遇，把素材找回來再剪。';
    if(bad){mistake(bad);return;}pause();enemyHP=Math.max(0,enemyHP-(turn<2?35:30));turn++;fx();log('剪輯反擊命中！怪物防護下降，生命剩 '+enemyHP+'。'+(turn<3?'下一回合，用另一個剪輯操作破盾。':'你拿回一顆星石！'));if(turn===3){won.add(active);rewards.push(encounters[active].name+'：'+encounters[active].skill);if(won.size===4)log('四顆星石集齊，回聲王國的故事回來了！可以下載素材筆記，最後換你創作。');}render();if(won.size===4&&!$('rpgExport')){const b=node('button','下載勇者冒險素材筆記',$('rpgSettings'));b.id='rpgExport';b.onclick=download;}};
  $('rpgSplit').onclick=()=>{let acc=0,index=clips.findIndex(s=>{const end=acc+duration(s);if(head>acc+.1&&head<end-.1)return true;acc=end;return false;});if(index<0){log('把播放頭放在片段內部，再按分割。');return;}stopEdit();const s=clips[index],cut=s.in+(head-acc)*s.speed;clips.splice(index,1,{...s,out:cut},{...s,key:++uid,in:cut});selected=clips[index+1].key;if(s.id==='wait')split=true;tracks();settings();preview=true;draw();log('分割完成。現在兩段仍在影片中，選取後刪除才能拿掉。');};
  $('rpgDelete').onclick=()=>{stopEdit();clips=clips.filter(s=>s.key!==selected);selected=clips[0]?.key||null;head=Math.min(head,total());tracks();settings();preview=true;draw();};
  function reorder(delta){const i=clips.findIndex(n=>n.key===selected);if(i<0||i+delta<0||i+delta>=clips.length)return;stopEdit();[clips[i],clips[i+delta]]=[clips[i+delta],clips[i]];head=0;tracks();draw();}
  $('rpgLeft').onclick=()=>reorder(-1);$('rpgRight').onclick=()=>reorder(1);
  $('rpgScrub').oninput=()=>{pause();head=Number($('rpgScrub').value);preview=true;watchStart=false;draw();$('rpgTime').textContent=head.toFixed(1)+'s / '+total().toFixed(1)+'s';};
  $('rpgRewind').onclick=()=>{pause();head=0;preview=true;watchStart=false;draw();};
  $('rpgPlay').onclick=()=>{if(playing){pause();return;}if(!clips.length)return;if(head>=total())head=0;if(head===0)watchStart=true;playing=true;preview=true;$('rpgPlay').textContent='⏸ 暫停冒險';if($('rpgSound').checked)tone();ensure();};
  let audio=null,gain=null,bellGain=null;function tone(){if(!audio){try{audio=new(window.AudioContext||window.webkitAudioContext)();gain=audio.createGain();gain.gain.value=0;gain.connect(audio.destination);const oscillator=audio.createOscillator();oscillator.frequency.value=220;oscillator.connect(gain);oscillator.start();const bell=audio.createOscillator();bell.frequency.value=784;bellGain=audio.createGain();bellGain.gain.value=0;bellGain.connect(audio.destination);bell.connect(bellGain);bell.start();}catch(_){return;}}audio.resume().catch(()=>{});gain.gain.value=playing?music/100*.035:0;}
  $('rpgSound').onchange=()=>{if($('rpgSound').checked&&playing)tone();if(!$('rpgSound').checked){if(gain)gain.gain.value=0;if(bellGain)bellGain.gain.value=0;}};
  function canMove(x,y){return x>0&&x<15&&y>0&&y<9&&(x!==5||y===3);}
  function move(dir){if(active>=0){log('戰鬥中請操作剪輯台；想探索可按回地圖。');return;}const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir];if(!d)return;if(canMove(player.x+d[0],player.y+d[1])){player.x+=d[0];player.y+=d[1];walking=time+.25;draw();ensure();}const e=encounters.find(e=>Math.abs(e.x-player.x)+Math.abs(e.y-player.y)<=1);$('rpgLocation').textContent=e?'附近：'+e.name:'探索回聲王國';}
  function interact(){if(active>=0)return;const i=encounters.findIndex(e=>Math.abs(e.x-player.x)+Math.abs(e.y-player.y)<=1);if(i>=0){encounter(i);return;}if(Math.abs(player.x-2)+Math.abs(player.y-8)<=2){hp=4;health();log('旅人說：怪物不怕亂加特效，怕的是「觀眾看得懂」。看每回合提示，先修改時間軸再出招。生命補滿！');}else log('靠近怪物旗子或營地旅人，再按對話。也可點下方地區卡進入遭遇。');}
  document.querySelectorAll('[data-rpg-move]').forEach(b=>b.onclick=()=>move(b.dataset.rpgMove));$('rpgInteract').onclick=interact;
  function returnMap(){pause();active=-1;preview=false;$('rpgLocation').textContent='回聲王國地圖';$('rpgTitle').textContent=won.size===4?'王國的故事回來了':'繼續探索，尋找星石';$('rpgInstruction').textContent='方向鍵移動、Enter 對話。選下一個地區，也可以重玩已完成的遭遇。';$('rpgSettings').replaceChildren();render();draw();if(won.size===4){const b=node('button','下載勇者冒險素材筆記',$('rpgSettings'));b.onclick=download;}}
  $('rpgRetry').onclick=()=>{if(active>=0)encounter(active);else log('先選一個地區，才能重玩遭遇。');};
  $('rpgMap').onclick=returnMap;$('rpgRest').onclick=()=>{hp=4;player={x:2,y:8};returnMap();health();log('回營地休息，生命補滿。星石保留，再去下一個地區吧。');};
  canvas.onkeydown=e=>{if(!document.documentElement.classList.contains('gate-ready')||($('tb')&&!$('tb').hidden))return;const d={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'}[e.key];if(d){e.preventDefault();move(d);}if(e.key==='Enter'){e.preventDefault();interact();}};
  canvas.onclick=e=>{if(active>=0)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*800/r.width,y=(e.clientY-r.top)*500/r.height;const i=encounters.findIndex(n=>Math.abs(x-(n.x*50+25))<35&&Math.abs(y-(n.y*50+25))<45);if(i>=0)encounter(i);canvas.focus();};
  function loop(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;time+=dt;if(playing){if(!document.documentElement.classList.contains('gate-ready')||($('tb')&&!$('tb').hidden))pause();else{head=Math.min(total(),head+dt);$('rpgScrub').value=head;$('rpgTime').textContent=head.toFixed(1)+'s / '+total().toFixed(1)+'s';if(head>=total()){if(watchStart)fullWatch=true;pause();log('預覽完成。事情的目的、危機、動作和結果都還在嗎？確認好就能反擊。');}}}if(gain){gain.gain.value=playing&&$('rpgSound').checked?music/100*.035:0;bellGain.gain.value=playing&&$('rpgSound').checked&&head>total()-2?cue/100*.025:0;}draw(dt);anim=visible&&!document.hidden?requestAnimationFrame(loop):0;}
  function ensure(){if(!anim&&visible&&!document.hidden){last=performance.now();anim=requestAnimationFrame(loop);}}
  new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)ensure();else{pause();cancelAnimationFrame(anim);anim=0;}},{threshold:.05}).observe(root);
  document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();cancelAnimationFrame(anim);anim=0;}else ensure();});
  function download(){const text='# 勇者冒險素材筆記\n\n'+[...won].sort().map(i=>'- '+encounters[i].name+'：'+encounters[i].skill).join('\n')+'\n\n## 我的冒險影片\n目的：取回星石\n危機：遇到怪物\n解決：修好時間軸，讓故事看得懂\n結果：拿回星石與歡呼\n\n## 下一堂剪映\n匯入遊戲錄影，先選鏡頭並排列；保留原因與結果；刪掉多餘等待；字幕不擋動作；音樂不蓋重點。\n';save('勇者冒險素材筆記.md',text);}
  function save(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('creationDownload').onclick=()=>{const labels=['目的','麻煩','解決','結果'];const fields=[...document.querySelectorAll('.creation-grid textarea')];save('我的四格剪輯計畫.md','# 我的冒險短片計畫\n\n'+fields.map((n,i)=>'## '+(i+1)+'. '+labels[i]+'\n'+n.value+'\n').join('\n')+'\n影片目標：15–30 秒。\n先選材與排列，再修剪、字幕、音量、預覽，最後在剪映輸出。\n');};
  document.querySelector('.class-route a[href="#moreWorlds"]').addEventListener('click',()=>{$('moreWorlds').open=true;});
  cards();health();tracks();log('歡迎來到回聲王國。這是一個原創回合制勇者冒險，四場遭遇、十二個剪輯戰鬥回合。');draw();
})();
